### ISSUE TITLE
Linux releases

### ISSUE THREAD

**Issue by Pokemod97** [Tuxality/maketmd#2]
Please package Linux binaries.

**Comment by yeah-its-gloria** [comment]
You can make those by yourself. Just install openssl and run `make`.

**Comment by Tuxality** [comment]
That's why _Makefile_ is provided, there is no point in providing such releases as most distros and its users have gcc/clang/whatever. Just make sure that you have OpenSSL dev pkg installed, then run _make_ and you are done...

If you have problems with compiling _maketmd_, just feel free to open new issue and provide detailed information.
